#!/usr/bin/env bash
#
# Retrieve the GitHub URL's for repositories that a given user has starred
#
# Written by: Derek Callaway [decal (AT) sdf {D0T} org]
# Created on: Fri Mar 30 01:11:35 DST 2018
# Tested via: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) Ubuntu 16.04.4 LTS
#

if [ ! "$2" ]
  then echo "usage: $0 USER REPO"
  echo
  echo  '  USER username of account on GitHub'
  echo  '  REPO repository for USER to get description of'
  
  exit 1
fi

curl "https://api.github.com/repos/${1}/${2}" 2>/dev/null | \ 
  grep '"description":'  | head -n 1 | cut -d ' :' -f2 | awk -F\" '{print$2}'

exit 0
