#!/usr/bin/env bash
#
# upd8 repo warez from git-map-clone
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Wed Jun 21 21:55:39 PDT 2017
#

### <== (o) dONUT MOD STUFFZ UNDER HERe (o) ==> ###

source inc/colors

[ "$GITHOSE_MODE_UMASK" ] && umask -- $GITHOSE_MODE_UMASK 

if [ ! $0 ]
  then echo "usage: $0 [USER]"

  exit 1
fi

[[ $GITHOSE_DEBUG -ne 0 ]] && set -x || set +x

readonly gitUser="$1"

# derp durp?
function errx_show() {
  echo -n -- "$1: " 

  perror -v -- $2

  return 0
}

# w00pz!
function errx_exit() {
  readonly reposPath=$(realpath $3)

  echo -n -- "$1: " 

  [ "$reposPath" ] && echo -n "${reposPath} "

  perror -v -- $2

  exit $2
}

# wtfark iz u d0in?
if [ ! -d $GITAA_PATH_CLONE ] 
  then echo "${purplef}$0${whitef}${boldon}:${boldoff} ${yellowf}${GITAA_PATH_CLONE} does not exist!${reset}"
  echo -e "${purplef}$0${whitef}${boldon}:${boldoff} ${yellowf}Are you sure you ran git-map-clone already?${reset}\n"

  exit 1
fi

# current werk
cd -- $GITAA_PATH_CLONE

if [ "$gitUser" ] 
  then declare -i count=0
  
  cd -- $gitUser

  for arepo in $(find "${GITAA_PATH_CLONE}/$gitUser" -maxdepth 1 -type d -not -name '.*' -and -not -name "$gitUser" -print)
    do declare foldr="$(realpath $arepo)"

    if [ -d "$foldr" ] 
      then count=$(( 1 + count ))
      
      cd -- "$foldr"
      
      git pull &
    fi
  done

  for ajob in `seq 1 $count`
    do wait %${ajob}
  done
else
  # roflcopterz tyme!@#
  for auser in $(find $GITAA_PATH_CLONE -maxdepth 1 -type d -not -name '.*' -print)
    do declare -i t00tsieRollPop=0

    for arepo in $(find "${GITAA_PATH_CLONE}/$(basename $auser)" -maxdepth 1 -type d -not -name '.*' -print)
      do cd -- $(realpath $arepo)

      git pull 2>/dev/null &

      cd ..

      t00tsieRollPop=$(( t00tsieRollPop + 1 ))
    done

    for lick in `seq 1 $t00tsieRollPop`
      do wait %${lick} |&> /dev/null
    done
  done
fi

exit 0
