#!/usr/bin/env bash
#
# Wrapper script to loop over command-line arguments..
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 15:44:55 EST 2017
#

# Uncomment the line below for debugging
#set -x

[ ! -d 'inc' ]  && [ -d '../inc' ] && cd ..

source -- inc/colors
source -- inc/regexes

export k=0

while [ $k -ne $(( ${#BASH_ARGV} - 2 )) ]
  do a="${BASH_ARGV[$k]}"
  k=$(( k + 1 ))

  lib/isgist ${BASH_ARGV[$(( ${#BASH_ARGV[*]} - 1 ))]} ${BASH_ARGV[$(( ${#BASH_ARGV} - 1 ))]} $a

  [ $? ] && exit $?
done
