#!/usr/bin/env bash
#
# Wrapper script to loop over command-line arguments..
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 15:44:55 EST 2017
#

[ $GITHOSE_DEBUG ] && set -x || set +x

[ -d '../inc' ] && cd .. || ( [ -d '../../inc' ] && cd ../.. )

source inc/colors && source inc/regexes

declare -i k=$(( ${#BASH_ARGV[*]} - 1 ))

while [[ $k -ne 0 ]]
  do k=$(( k - 1 ))

  lib/typeof $1 ${BASH_ARGV[$k]} # 2>/dev/null

  [ $? ] && exit
done

