#!/usr/bin/env bash
#
# Handle each command-line argument as it is invoked from the driver script..
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 15:44:55 EST 2017
#

[[ $GITHOSE_DEBUG -ne 0 ]] && set -x || set +x

if [ ! -d 'inc' ]  
  then if [ -d '../inc' ] 
    then cd ..
  fi
fi

source -- inc/colors
source -- inc/regexes

if [ ! "$1" ] && [ "${1:0:5}" != 'clone' ] && [ "${1:0:4}" != 'pull' ]
  then echo -e "${yellowf}usage${boldon}${whitef}:${boldoff} ${cyanf}$0 ${purplef}<command>${reset}"

  echo "${purplef}${boldon}clone${reset}  store all of user's repositories in a new directory named after them${reset}"
  echo "${purplef}${boldon}pull${reset}   fetch changes for remote user's repositories into the local branches${reset}"

  echo "${invon}ex.${invoff} ${greenf}${italicson}-githose-clone decal${reset}"

  exit -1
fi

if [[ $1 =~ $GITAA_REPO_REGEX || $1 =~ $GITAA_GITS_REGEX || $1 =~ $GITAA_LINK_REGEX ]]
  then if [[ $1 =~ GITAA_LINK_REGEX ]]
    then export aUser = #
  else
    export aUser = "$3"
  fi
  
  [[ "$2" =~ ^clone ]] && lib/githose/clone -- $aUser
  [[ "$2" =~ ^pull ]] && lib/githose/clone -- $aUser
fi

if [[ $1 =~ $GITAA_GIST_REGEX ]]
  then if [[ $1 =~ $GITAA_LINK_REGEX ]] 
    then export bUser = #
  else
    export bUser = "$3"
  fi

  [[ "$2" =~ ^clone ]] && lib/gisthose/clone -- $bUser
  [[ "$2" =~ ^pull ]] && lib/gisthose/pull -- $bUser
fi
