#!/usr/bin/env bash
#
# Determine whether to fetch gists from GitHub over HTTPS
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 16:31:19 EST 2017
#

[ $GITHOSE_DEBUG ] && set -x || set +x

[ -d '../inc' ] && cd .. || ( [ -d '../../inc' ] && cd ../.. )

source inc/inits && source inc/usages && source inc/sysexits

#if ! [[ $1 =~ ^set ]]
#  then if ( ! [ $1 ] && [ $2 ] )
#    then [[ $GITHOSE_ARGV0 =~ git ]] && githoseUsage || gisthoseUsage
#  fi
#fi

if [[ $1 =~ ^help ]] 
  then genericUsage 
else
  if [[ $1 =~ ^set ]] 
    then setUsage
  else
    lib/misc/set "$2" "$3"
  fi
fi

if [[ $GITHOSE_ARGV0 =~ gist ]] 
  then export githosePath='gisthose'
else 
  if [[ $GITHOSE_ARGV0 =~ git ]]
    then export githosePath='githose'
  else 
   [[ $GITHOSE_ARGV0 =~ grist ]] && export githosePath='gristhose'
  fi
fi

[ ! "$githosePath" ] && export githosePath='githose'

if [[ $1 =~ ^clone ]]
  then if [[ $2 =~ ^help ]] 
    then [[ $GITHOSE_ARGV0 =~ grist ]] && gristhoseCloneUsage
  else
    lib/${githosePath}/clone $2
  fi    
else
  if [[ $1 =~ ^clone ]]
    then if [[ $2 =~ ^help ]] 
      then [[ $GITHOSE_ARGV0 =~ git ]] && githoseCloneUsage || gisthoseCloneUsage
    else 
      lib/${githosePath}/clone $2 
    fi
  else 
    if [[ $1 =~ ^pull ]] && ! ( [[ $2 =~ ^-a$ ]] || [[ $2 =~ ^--all$ ]] )
      then lib/${githosePath}/pull $2 
    else
      if ( [[ $2 =~ ^-a$ ]] || [[ $2 =~ ^--all$ ]] )
        then lib/${githosePath}/pull 
      else
        [[ $GITHOSE_ARGV0 =~ gist ]] && gisthoseUsage || gisthoseUsage
      fi
    fi
  fi

  if [[ $1 =~ ^view ]] && ! ( [[ $2 =~ ^-a$ ]] || [[ $2 =~ ^--all$ ]] )
    then lib/${githosePath}/pull $2
  else
    if ( [[ $2 =~ ^-a$ ]] || [[ $2 =~ ^--all$ ]] )
      then lib/${githosePath}/pull
    else
      [[ $GITHOSE_ARGV0 =~ gist ]] && gisthoseUsage || gisthoseUsage
    fi
  fi
fi
