#!/usr/bin/env bash
#
# perform ANSI color escape codes for gitaa
# 
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 16:24:24 EST 2017
#

#
# This file was "forked" from cirrusUK's gists on GitHub
# https://gist.githubusercontent.com/cirrusUK/9494694/raw
#

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

if [ ! $esc ] || [ ! $reset ]
  then export esc=""

  export blackf="${esc}[30m"   redf="${esc}[31m"   greenf="${esc}[32m"
  export yellowf="${esc}[33m"  bluef="${esc}[34m"  purplef="${esc}[35m"
  export cyanf="${esc}[36m"    whitef="${esc}[37m"
  export blackb="${esc}[40m"   redb="${esc}[41m"   greenb="${esc}[42m"
  export yellowb="${esc}[43m"  blueb="${esc}[44m"  purpleb="${esc}[45m"
  export cyanb="${esc}[46m"    whiteb="${esc}[47m"
  export boldon="${esc}[1m"    boldoff="${esc}[22m"
  export italicson="${esc}[3m" italicsoff="${esc}[23m"
  export ulon="${esc}[4m"      uloff="${esc}[24m"
  export invon="${esc}[7m"     invoff="${esc}[27m"
  export reset="${esc}[0m"
fi
