#!/usr/bin/env bash
#
# Initialize per-system setup variables
# 
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Fri Nov 11 22:28:23 EST 2016
#

if [ ! $initLoaded ] 
  then declare -r -i initLoaded=1
  declare -r -i -x verboseFlag=1
  declare -r -x githosePath='githose'

  # GNU parallel GOT's dis many Shakezpeer typewriter monkeys
  export GITHOSE_NUM_JOBS=0
  
  for proc_core_cnt in $(egrep -i '^cpu cores' /proc/cpuinfo | awk -F: '{print($2);}')
    do export GITHOSE_NUM_JOBS=$(( GITHOSE_NUM_JOBS + proc_core_cnt ))
  done
fi
