#!/usr/bin/env bash
#
# Initialize per-system setup variables
# 
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Fri Nov 11 22:28:23 EST 2016
#

if [ ! $initLoaded ] 
  # GNU parallel GOT's dis many Shakezpeer typewriter monkeys
  then export GITHOSE_NUM_JOBS=$( grep 'cpu cores' /proc/cpuinfo | cut -d ':' -f2 | head -1 | sed 's/[ ]*$//;s/^[ ]*//' )
  declare -i initLoaded=1 
  declare -i verboseFlag=1 
  declare githosePath='githose'
fi
