#!/usr/bin/env bash
#
# Get hardware configuration for gitaa
# 
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Fri Nov 11 22:28:23 EST 2016
#

function initSetup()
{
  declare -ir setup_cpu_cores=$( grep 'cpu cores' /proc/cpuinfo | head -1 | awk -F: '{print($2);}' )

  return 
}

[[ ${setup_cpu_cores} == 0 ]] && initSetup && echo -ne "${reset}"

