#!/usr/bin/env bash
#
# Display command-line usage information in general and for specific sub-commands
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 22:48:36 EST 2017
#

[[ $GITHOSE_DEBUG -ne 0 ]] && set -x || set +x
[ -d '../inc' ] && cd .. || ( [ -d '../../inc' ] && cd ../.. )

source -- inc/colors

function gristhoseUsage() {
  cat etc/gristhose.motd 2>/dev/null
  echo -n "${boldon}${italicon}${whitef}"
  cat etc/gristhose.issue 2>/dev/null

  echo
  echo -e "${reset}${yellowf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}USERNAME${reset} ${blueb}${cyanf}${italicson}[...]${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}get all user's repositories and gists simultaneously${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch updates on all user's repositories and gists${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}USERNAME${reset} ${italicon}${yellowf}can be one/multiple user argument(s):${reset}"
  echo "    ${bluef}user${reset}  ${italicon}${yellowf}user name of account on GitHub${reset}"
  echo
  echo "${invon}ex.${invoff} ${greenf}${italicon}${0} clone decal${reset}"
  echo

  return
}

function gisthoseUsage() {
  cat etc/gisthose.motd 2>/dev/null
  echo -n "${boldon}${italicon}${whitef}"
  cat etc/gisthose.issue 2>/dev/null

  echo
  echo -e "${reset}${yellowf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}USERNAME${reset} ${blueb}${cyanf}${italicson}[...]${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}store all of user's gists in a new directory named after them${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch changes for remote user's gists into local replicas${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}USERNAME${reset} ${italicon}${yellowf}can be one/multiple user argument(s):${reset}"
  echo "    ${bluef}user${reset}  ${italicon}${yellowf}user name of account on GitHub${reset}"
  echo
  echo "${invon}ex.${invoff} ${greenf}${italicon}${0} clone imakewebthings${reset}"
  echo

  return
}

function githoseUsage() {
  cat etc/githose.motd 2>/dev/null
  echo -n "${boldon}${italicon}${whitef}"
  cat etc/githose.issue 2>/dev/null

  echo
  echo -e "${reset}${yellowf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}USERNAME${reset} ${blueb}${cyanf}${italicson}[...]${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}download all user's code repositories${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch changes to user's code repositories${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}USERNAME${reset} ${italicon}${yellowf}can be a flag or one/multiple user argument(s):${reset}"
  echo "    ${bluef}user${reset}       ${italicon}${yellowf}user name of account on GitHub${reset}"
  echo "    ${greenf}-a, --all${reset}  ${italicon}${yellowf}fetch latest updates to all local repositories${reset}"
  echo
  echo "${invon}ex.${invoff} ${greenf}${italicon}${0} clone juliangruber vagg${reset}"
  echo

  return
}

function genericUsage() {
  cat etc/githose.motd 2>/dev/null
  echo -n "${boldon}${italicon}${whitef}"
  cat etc/githose.issue 2>/dev/null

  echo
  echo -e "${reset}${yellowf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}ARGUMENTS${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one of the commands as explained below:${reset}"
  echo "    ${greenf}githose${reset}     ${italicon}${yellowf}download all user's code repositories under \$HOME ${reset}"
  echo "    ${greenf}gisthose${reset}    ${italicon}${yellowf}download all user's gists code texts${reset}"
  echo "    ${greenf}gristhose${reset}   ${italicon}${yellowf}download all user's repositories and gists${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}ARGUMENTS${reset}  ${italicon}${yellowf}similar to ${reset}${whitef}${bold}git(1)${reset} ${italicon}${yellowf}command usage:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}get all user's repositories and/or gists${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch updates on all user's repositories and/or gists${reset}"
  echo
  echo "${invon}Note: if possible command arguments (clone and pull) run in parallel..${reset}"
  echo

  return
}
