#!/usr/bin/env bash
#
# Display command-line usage information in general and for specific sub-commands
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Sat Jan  7 22:48:36 EST 2017
#

[[ $GITHOSE_DEBUG -ne 0 ]] && set -x || set +x
[ -d '../inc' ] && cd .. || ( [ -d '../../inc' ] && cd ../.. )

source -- inc/colors

function gristhoseUsage() {
  echo
  echo -e "${cyanf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}ARGUMENTS${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}get all user's repositories and gists simultaneously${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch updates on all user's repositories and gists${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}USERNAME${reset} ${italicon}${yellowf}can be one or more of any one of the following:${reset}"
  echo "    ${greenf}user${reset}  ${italicon}${yellowf}account user name on GitHub${reset}"
  echo
  echo "${invon}ex.${invoff} ${greenf}${italicon}${0} clone decal${reset}"
  echo

  return
}

function gisthoseUsage() {
  echo
  echo -e "${cyanf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}USERNAME${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}store all of user's gists in a new directory named after them${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch changes for remote user's gists into local replicas${reset}"
  echo "    ${greenf}help${reset}   ${italicon}${yellowf}show more detailed help and command-line usage info specific to sub-commands${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}USERNAME${reset} ${italicon}${yellowf}can be one or more of any one of the following:${reset}"
  echo "    ${greenf}user${reset}  ${italicon}${yellowf}account user name on GitHub${reset}"
  echo
  echo "${invon}ex.${invoff} ${greenf}${italicon}${0} clone imakewebthings${reset}"
  echo

  return
}

function githoseUsage() {
  echo 
  echo -e "${cyanf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}USERNAME${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}clone${reset}  ${italicon}${yellowf}download all user's code repositories under \$HOME ${reset}"
  echo "    ${greenf}pull${reset}   ${italicon}${yellowf}fetch changes to user's code repositories${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}USERNAME${reset} ${italicon}${yellowf}can be one or more of any one of the following:${reset}"
  echo "    ${greenf}user${reset}  ${italicon}${yellowf}account user name on GitHub${reset}"
  echo
  echo "${invon}ex.${invoff} ${greenf}${italicon}${0} clone juliangruber vagg${reset}"
  echo

  return
}

function genericUsage() {
  echo
  echo -e "${cyanf}${invon}usage${invoff}${boldon}${whitef}:${boldoff} ${greenf}${0} ${blueb}${blackf}${boldon}COMMAND${reset} ${blueb}${blackf}${boldon}ARGUMENTS${reset}"
  echo
  echo "  ${blueb}${blackf}${boldon}COMMAND${reset}  ${italicon}${yellowf}one command strings explained below:${reset}"
  echo "    ${greenf}githose${reset}  ${italicon}${yellowf}download all user's code repositories under \$HOME ${reset}"
  echo "    ${greenf}gisthose${reset}   ${italicon}${yellowf}download all user's gists code texts${reset}"
  echo "    ${greenf}gristhose${reset}   ${italicon}${yellowf}download all user's repositories and gists${reset}"
  echo

  return
}

