#!/usr/bin/env bash
#
# Anononymously and asynchronously perform git clone operations on all of a 
# GitHub user's public gist and repository warez in a parallelized manner!
#
# Derek Callaway <decal {AT} sdf {D0T} org>
#
# Thu Feb  9 19:06:48 EST 2017
#

( [ "$GITHOSE_DEBUG" ] && [ $GITHOSE_DEBUG -ne 0 ] ) && set -x || set +x

source etc/gristhose.conf

declare gristUsers="${BASH_ARGV[*]}"
declare -i gristCount=0

for auser in $gristUsers
  do gristCount+=2
  ./githose clone $auser &
  ./gisthose clone $auser &
done

for i in $(seq 1 $gristCount)
  do wait %${i}
done

